/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.airavata.cloud.aurora.client.sdk;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

// TODO: Auto-generated Javadoc
/**
 * The Enum ResponseCode.
 */
public enum ResponseCode implements org.apache.thrift.TEnum {
  
  /** The invalid request. */
  INVALID_REQUEST(0),
  
  /** The ok. */
  OK(1),
  
  /** The error. */
  ERROR(2),
  
  /** The warning. */
  WARNING(3),
  
  /** The auth failed. */
  AUTH_FAILED(4),
  /**
   * Raised when a Lock-protected operation failed due to lock validation.
   */
  LOCK_ERROR(5),
  /**
   * Raised when a scheduler is transiently unavailable and later retry is recommended.
   */
  ERROR_TRANSIENT(6);

  /** The value. */
  private final int value;

  /**
   * Instantiates a new response code.
   *
   * @param value the value
   */
  private ResponseCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   *
   * @return the value
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   *
   * @param value the value
   * @return null if the value is not found.
   */
  public static ResponseCode findByValue(int value) { 
    switch (value) {
      case 0:
        return INVALID_REQUEST;
      case 1:
        return OK;
      case 2:
        return ERROR;
      case 3:
        return WARNING;
      case 4:
        return AUTH_FAILED;
      case 5:
        return LOCK_ERROR;
      case 6:
        return ERROR_TRANSIENT;
      default:
        return null;
    }
  }
}
