/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.airavata.sga.commons.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum DataStagingDirection implements org.apache.thrift.TEnum {
  INPUT(0),
  OUTPUT(1);

  private final int value;

  private DataStagingDirection(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DataStagingDirection findByValue(int value) { 
    switch (value) {
      case 0:
        return INPUT;
      case 1:
        return OUTPUT;
      default:
        return null;
    }
  }
}
