/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.airavata.sga.commons.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ExperimentPriority implements org.apache.thrift.TEnum {
  NORMAL(0),
  URGENT(1);

  private final int value;

  private ExperimentPriority(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ExperimentPriority findByValue(int value) { 
    switch (value) {
      case 0:
        return NORMAL;
      case 1:
        return URGENT;
      default:
        return null;
    }
  }
}
